#   Author: Mateusz Jarkiewicz - mjarkiew.github.io

apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-helloworld-deployment
  labels:
    app: c-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c-helloworld
  template:
    metadata:
      labels:
        app: c-helloworld
    spec:
      containers:
      - name: c-helloworld
        image: mjarkiew/c-helloworld-container:1.0
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: c-helloworld-service
spec:
  selector:
    app: c-helloworld
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7776
      targetPort: 7777
      nodePort: 30042